### ISSUE TITLE
Name might be causing low discoverability

### ISSUE THREAD

**Issue by Sayayaya** [onlymash/moebooru-android#2]
Hello,
 I have only just found this app, and that is a problem because I was looking for an mBooru replacement for Android for well over a year, actively googling for things like booru app github android etc. 

In the past I have seen mentions of moebooru app but when you search for moebooru you find the Website system instead.

I have the feeling that if this is the case for me it's likely for a lot of other people as well. Perhaps if not the name, at least including the word 'booru' on its own in the readme would help other people discover the app as I don't think most people know the name of the software.

**Comment by DonaldTsang** [comment]
@Sayayaya I recommend that you fork the project then rename your fork, add an issues page and you are done. Also "moebooru-android" is pretty easy to understand as an app for moebooru
